# Use official Node image
FROM node:23-alpine

# Set working directory
WORKDIR /app

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the app port
EXPOSE 5001

# Start the server
CMD ["node", "src/index.js"]
